/** Merkezi marka kimliği — tek yerden yönetilir */
export const brand = {
  name: "DNZ İnşaat",
  shortName: "DNZ",
  tagline: "İnşaat Malzemeleri & Asma Tavan",
  description:
    "DNZ İnşaat Ankara Gölbaşı: alçıpan, alçı, boya, galvaniz profil, kutu profil, ABS, UMS, clip-in / petek / karolam / taşyünü / vinil asma tavan, plastik lambiri, bölme duvar, giydirme duvar, seramik, parke, malzeme, yedek parça, kombi parçası, elektrik ve su tamiratı, ev-okul-ofis tadilatı, anahtar teslim.",
  /** Vercel/DNS: dnzinşaat.com.tr punycode */
  url: "https://www.xn--dnzinaat-rwb.com.tr",
  domainDisplay: "dnzinşaat.com.tr",
  email: "dnzyapimalzemeleri@gmail.com",
  phone: "0533 611 06 15",
  phoneTel: "+905336110615",
  address: "Karşıyaka Mah. Şehit Ali Gaffar Okkan Cad. No: 42/A, Gölbaşı / Ankara",
  hours: "Pazartesi – Cumartesi · 09:00 – 18:00",
  keywords: [
    "DNZ İnşaat",
    "DNZ inşaat malzemeleri",
    "alçıpan",
    "alçı",
    "boya",
    "profil",
    "galvaniz profil",
    "kutu profil",
    "ABS profil",
    "UMS profil",
    "asma tavan",
    "alçıpan asma tavan",
    "karolam tavan",
    "karolam asma tavan",
    "petek asma tavan",
    "clipin asma tavan",
    "klipin asma tavan",
    "clip-in tavan",
    "taşyünü asma tavan",
    "taşyünü tavan",
    "vinil asma tavan",
    "plastik lambiri",
    "plastik tavan",
    "metal tavan",
    "bölme duvar",
    "alçıpan bölme duvar",
    "alçıpan giydirme duvar",
    "seramik",
    "parke",
    "malzeme",
    "yedek parça",
    "kombi parçası",
    "elektrik tamiratı",
    "su tamiratı",
    "ev tadilatı",
    "okul tadilatı",
    "ofis tadilatı",
    "anahtar teslim",
    "Ankara asma tavan",
    "Gölbaşı inşaat malzemeleri",
    "Ankara alçıpan",
  ],
  services: [
    "Alçıpan asma tavan",
    "Alçıpan giydirme duvar",
    "Alçıpan bölme duvar",
    "Alçı ve boya",
    "Galvaniz profil",
    "Kutu profil",
    "ABS / UMS profil",
    "Clip-in / klipin asma tavan",
    "Petek asma tavan",
    "Karolam asma tavan",
    "Taşyünü asma tavan",
    "Vinil asma tavan",
    "Plastik lambiri",
    "Seramik ve parke",
    "Elektrik tamiratı",
    "Su tamiratı",
    "Kombi yedek parça",
    "Ev tadilatı",
    "Okul tadilatı",
    "Ofis tadilatı",
    "Anahtar teslim uygulama",
    "Malzeme satışı",
  ],
  colors: {
    ink: "#F4F6F9",
    anthracite: "#FFFFFF",
    slate: "#E2E8F0",
    mist: "#64748B",
    bone: "#0F172A",
    gold: "#D97706",
    goldLight: "#F59E0B",
    navy: "#0B2C5E",
  },
} as const;

export const checkoutConfig = {
  vatRate: 0.2,
  shippingFlat: 250,
  freeShippingThreshold: 15000,
  currency: "TRY" as const,
};
