/** Merkezi marka kimliği — tek yerden yönetilir */
export const brand = {
  name: "DNZ İnşaat",
  shortName: "DNZ",
  tagline: "İnşaat Malzemeleri & Asma Tavan",
  description:
    "DNZ İnşaat malzemeleri: alçıpan, galvaniz profil, clip-in / klipin asma tavan, taşyünü tavan, metal tavan, plastik tavan, karolam, bölme duvar ve malzeme satışı. Ankara Gölbaşı.",
  /** Teknik URL — Vercel/DNS için punycode (dnzinşaat.com.tr) */
  url: "https://www.xn--dnzinaat-rwb.com.tr",
  /** Tarayıcıda görünen ad */
  domainDisplay: "dnzinşaat.com.tr",
  email: "info@dnzinsaat.com",
  phone: "0533 611 06 15",
  phoneTel: "+905336110615",
  address: "Karşıyaka Mah. Şehit Ali Gaffar Okkan Cad. No: 42/A, Gölbaşı / Ankara",
  hours: "Pazartesi – Cumartesi · 09:00 – 18:00",
  keywords: [
    "DNZ İnşaat",
    "DNZ inşaat malzemeleri",
    "alçıpan",
    "alçıpan asma tavan",
    "profil",
    "galvaniz profil",
    "clipin asma tavan",
    "klipin asma tavan",
    "clip-in tavan",
    "taşyünü tavan",
    "taşyünü asma tavan",
    "bölme duvar",
    "alçıpan bölme duvar",
    "metal tavan",
    "plastik tavan",
    "karolam asma tavan",
    "asma tavan malzemeleri",
    "Ankara asma tavan",
    "Gölbaşı inşaat malzemeleri",
  ],
  services: [
    "Alçıpan asma tavan",
    "Alçıpan ışık bandı",
    "Taşyünü asma tavan",
    "Karolam asma tavan",
    "Clip-in / klipin asma tavan",
    "Metal tavan",
    "Plastik tavan",
    "Bölme duvar",
    "Galvaniz profil",
    "Bağlı malzeme satışı",
  ],
  colors: {
    ink: "#F4F6F9",
    anthracite: "#FFFFFF",
    slate: "#E2E8F0",
    mist: "#64748B",
    bone: "#0F172A",
    gold: "#D97706",
    goldLight: "#F59E0B",
    navy: "#0B2C5E",
  },
} as const;

export const checkoutConfig = {
  vatRate: 0.2,
  shippingFlat: 250,
  freeShippingThreshold: 15000,
  currency: "TRY" as const,
};
